### ISSUE TITLE
Module [web_search_date_range], function " _compute_xml_id" error!!

### ISSUE THREAD

**Issue by devinhuang** [Numigi/odoo-web-addons#45]
In module **web_search_date_range**, `search_date_range.py` line 26, it should use `('res_id', '=', range_type.id)`, otherwise when use **search more**, it raise singleton error.

**Comment by ddufresne** [comment]
@devinhuang thanks for the bug report. Fixed in https://github.com/Numigi/odoo-web-addons/pull/47
